// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5WXOf1RB6PDv8eeb5YTL-CwQXi2HbF1o',
    appId: '1:142558747235:web:2d24a87f4160c42517f656',
    messagingSenderId: '142558747235',
    projectId: 'ventevitement-5d6bc',
    authDomain: 'ventevitement-5d6bc.firebaseapp.com',
    storageBucket: 'ventevitement-5d6bc.appspot.com',
    measurementId: 'G-J5CKJTZ6J9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGNfXQvjbZpbk8Vb1az9e9l4RlAozf1Ec',
    appId: '1:142558747235:android:db0a81c226f2292e17f656',
    messagingSenderId: '142558747235',
    projectId: 'ventevitement-5d6bc',
    storageBucket: 'ventevitement-5d6bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsmTfXOdGcWBrrpsRnT_KXPMbax97kWmY',
    appId: '1:142558747235:ios:65af19ec6242434b17f656',
    messagingSenderId: '142558747235',
    projectId: 'ventevitement-5d6bc',
    storageBucket: 'ventevitement-5d6bc.appspot.com',
    iosBundleId: 'com.example.venteVitment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsmTfXOdGcWBrrpsRnT_KXPMbax97kWmY',
    appId: '1:142558747235:ios:65af19ec6242434b17f656',
    messagingSenderId: '142558747235',
    projectId: 'ventevitement-5d6bc',
    storageBucket: 'ventevitement-5d6bc.appspot.com',
    iosBundleId: 'com.example.venteVitment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5WXOf1RB6PDv8eeb5YTL-CwQXi2HbF1o',
    appId: '1:142558747235:web:0d71ac18a5a5b9b017f656',
    messagingSenderId: '142558747235',
    projectId: 'ventevitement-5d6bc',
    authDomain: 'ventevitement-5d6bc.firebaseapp.com',
    storageBucket: 'ventevitement-5d6bc.appspot.com',
    measurementId: 'G-8PY0BZW8FR',
  );

}